### ISSUE TITLE
Exclude from Source Tree

### ISSUE THREAD

**Issue by lukeolney** [mufeedvh/code2prompt#14]
Is it possible to add an argument so that any excluded files/folders/extensions are also excluded from the source tree?

I am currently working with some folders that have thousands of .npy files, or .wav, etc, and this means the source tree can get a little bit heavy!

Thanks for this great tool!

**Comment by mufeedvh** [comment]
Just implemented this! Usage:

```
code2prompt path/to/codebase --exclude="*.npy,*.wav" --exclude-from-tree
```

Thank you for the feature request! ❤️ 🙌
