### ISSUE TITLE
I want to exclude files and directories listed in .gitignore

### ISSUE THREAD

**Issue by yasainet** [mufeedvh/code2prompt#25]
I want to exclude files and directories listed in .gitignore

node_modules/
venv/

I've specified them in .gitignore as above, but code2prompt reads them without excluding them.

Should I specify them directly using `--exclude`?

In that case, should I specify `--exclude /**/node_modules/, /**/venv/`?

I look forward to your reply.

**Comment by mufeedvh** [comment]
Nope, `.gitignore` should work, I just tested it and can confirm that it works even if the `.gitignore` file is nested. I am closing this issue but if you can provide your directory structure (`tree` command output), I can take a look at this again. Thank you!
