### ISSUE TITLE
Provide precompiled binaries

### ISSUE THREAD

**Issue by ngirard** [mufeedvh/code2prompt#3]
Hey @mufeedvh,

Thanks for involving yourself into this nice project !

Could you please consider providing precompiled binaries through GitHub Actions ?

Cheers

**Comment by mufeedvh** [comment]
Thanks! and Done!

Here you go: https://github.com/mufeedvh/code2prompt/releases/tag/v1.0.0 🎉

**Comment by ngirard** [comment]
Wow ! Thank you so much !
