### ISSUE TITLE
--exclude in new v2.x does not work as instructed

### ISSUE THREAD

**Issue by elvismdev** [mufeedvh/code2prompt#44]
Upgraded from v1.x to v2.x and tried this command:

`code2prompt ./ --exclude="vendor,node_modules,build,composer.lock,package-lock.json,code2prompt.md" --exclude-from-tree --output=code2prompt.md`

But all the excluded files are included in the output.

**Comment by Gaket** [comment]
Hi! It looks like you're using the glob patterns wrong, I made the same mistake. Here is the explanation:
https://github.com/mufeedvh/code2prompt/issues/31#issuecomment-2216852875

Should be like:
```code2prompt <pathtoyourcodebase> --exclude "**/package.json"```

**Comment by LinuxIsCool** [comment]
How to exclude `node_modules/` directory?
